#!/bin/bash

CONTAINER_PATH="deployments/docker/container.sh"

# container
sed -i "s|{{ MONGO_URI }}|$MONGO_URI|g" $CONTAINER_PATH
sed -i "s|{{ TELEGRAM_BOT_TOKEN }}|$TELEGRAM_BOT_TOKEN|g" $CONTAINER_PATH
sed -i "s|{{ TELEGRAM_REPORT_CHAT_ID }}|$TELEGRAM_REPORT_CHAT_ID|g" $CONTAINER_PATH
sed -i "s|{{ IMAGE_NAME }}|$IMAGE_NAME|g" $CONTAINER_PATH
sed -i "s|{{ IMAGE_NAME_RAW }}|$IMAGE_NAME_RAW|g" $CONTAINER_PATH
sed -i "s|{{ STICKERSET_TITLE }}|$STICKERSET_TITLE|g" $CONTAINER_PATH
sed -i "s|{{ STICKERSET_OWNER_ID }}|$STICKERSET_OWNER_ID|g" $CONTAINER_PATH
sed -i "s|{{ STICKERSET_DEFAULT_IMAGE }}|$STICKERSET_DEFAULT_IMAGE|g" $CONTAINER_PATH
sed -i "s|{{ APP_NAME }}|$APP_NAME|g" $CONTAINER_PATH